CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     UUID         NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    display_name  VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_users_public_id
        UNIQUE (public_id),

    CONSTRAINT uq_users_email
        UNIQUE (email),

    CONSTRAINT ck_users_email_not_blank
        CHECK (LENGTH(TRIM(email)) > 0),

    CONSTRAINT ck_users_email_lowercase
        CHECK (email = LOWER(email)),

    CONSTRAINT ck_users_display_name_not_blank
        CHECK (LENGTH(TRIM(display_name)) > 0),

    CONSTRAINT ck_users_role
        CHECK (role IN ('USER', 'ADMIN'))
);