-- ItineraryItem only represents an ordered Place in the working itinerary.
-- Distance, travel time, timeline, score, warnings and AI metadata are intentionally deferred.

CREATE TABLE itinerary_items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id    UUID        NOT NULL,
    itinerary_id BIGINT      NOT NULL,
    place_id     BIGINT      NOT NULL,
    sequence_no  INTEGER     NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_itinerary_items_public_id
        UNIQUE (public_id),

    CONSTRAINT uq_itinerary_items_itinerary_place
        UNIQUE (itinerary_id, place_id),

    CONSTRAINT uq_itinerary_items_itinerary_sequence
        UNIQUE (itinerary_id, sequence_no),

    CONSTRAINT fk_itinerary_items_itinerary
        FOREIGN KEY (itinerary_id)
            REFERENCES itineraries (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_itinerary_items_place
        FOREIGN KEY (place_id)
            REFERENCES places (id)
            ON DELETE RESTRICT,

    CONSTRAINT ck_itinerary_items_sequence_positive
        CHECK (sequence_no > 0),

    CONSTRAINT ck_itinerary_items_timestamp_order
        CHECK (updated_at >= created_at)
);

CREATE INDEX idx_itinerary_items_place_id
    ON itinerary_items (place_id);
