CREATE TABLE trips
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id              UUID           NOT NULL,
    user_id                BIGINT         NOT NULL,

    trip_date              DATE           NOT NULL,
    start_time             TIME           NOT NULL,
    end_time               TIME           NOT NULL,
    budget                 NUMERIC(12, 2) NOT NULL,

    start_location_label   VARCHAR(255)   NOT NULL,
    start_latitude         NUMERIC(10, 7) NOT NULL,
    start_longitude        NUMERIC(10, 7) NOT NULL,

    travel_pace            VARCHAR(20)    NOT NULL,
    environment_preference VARCHAR(20)    NOT NULL,

    created_at             TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_trips_public_id
        UNIQUE (public_id),

    CONSTRAINT fk_trips_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE RESTRICT,

    CONSTRAINT ck_trips_time_order
        CHECK (start_time < end_time),

    CONSTRAINT ck_trips_duration
        CHECK (
            end_time - start_time >= INTERVAL '1 hour'
            AND end_time - start_time <= INTERVAL '18 hours'
),

    CONSTRAINT ck_trips_budget
        CHECK (
            budget >= 0
            AND budget <= 100000000
        ),

    CONSTRAINT ck_trips_start_location_label
        CHECK (
            LENGTH(BTRIM(start_location_label)) > 0
        ),

    CONSTRAINT ck_trips_start_latitude
        CHECK (
            start_latitude BETWEEN -90 AND 90
        ),

    CONSTRAINT ck_trips_start_longitude
        CHECK (
            start_longitude BETWEEN -180 AND 180
        ),

    CONSTRAINT ck_trips_travel_pace
        CHECK (
            travel_pace IN (
                'RELAXED',
                'BALANCED',
                'FAST'
            )
        ),

    CONSTRAINT ck_trips_environment_preference
        CHECK (
            environment_preference IN (
                'INDOOR',
                'OUTDOOR',
                'MIXED'
            )
        ),

    CONSTRAINT ck_trips_timestamp_order
        CHECK (
            updated_at >= created_at
        )
);

CREATE INDEX idx_trips_user_id
    ON trips (user_id);