CREATE TABLE place_images
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id    BIGINT       NOT NULL,
    storage_key VARCHAR(255) NOT NULL,
    url         VARCHAR(1000) NOT NULL,
    alt_text    VARCHAR(255),
    is_primary  BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order  INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_place_images_place
        FOREIGN KEY (place_id)
            REFERENCES places (id)
            ON DELETE CASCADE,

    CONSTRAINT uq_place_images_place
        UNIQUE (place_id),

    CONSTRAINT uq_place_images_storage_key
        UNIQUE (storage_key),

    CONSTRAINT ck_place_images_storage_key_not_blank
        CHECK (LENGTH(BTRIM(storage_key)) > 0),

    CONSTRAINT ck_place_images_url_not_blank
        CHECK (LENGTH(BTRIM(url)) > 0),

    CONSTRAINT ck_place_images_mvp_primary
        CHECK (is_primary = TRUE),

    CONSTRAINT ck_place_images_mvp_sort_order
        CHECK (sort_order = 0)
);
