CREATE TABLE itineraries
(
    id                              BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    public_id                       UUID           NOT NULL,
    user_id                         BIGINT         NOT NULL,
    trip_id                         BIGINT         NOT NULL,

    trip_public_id_snapshot         UUID           NOT NULL,
    trip_updated_at_snapshot        TIMESTAMPTZ    NOT NULL,

    trip_date                       DATE           NOT NULL,
    window_start                    TIME           NOT NULL,
    window_end                      TIME           NOT NULL,

    origin_latitude                 NUMERIC(10, 7) NOT NULL,
    origin_longitude                NUMERIC(10, 7) NOT NULL,

    travel_pace                     VARCHAR(20)    NOT NULL,
    environment_preference          VARCHAR(20)    NOT NULL,

    initial_budget                  NUMERIC(12, 2) NOT NULL,
    total_estimated_cost            NUMERIC(12, 2) NOT NULL,
    remaining_budget                NUMERIC(12, 2) NOT NULL,

    total_distance_km               NUMERIC(10, 3) NOT NULL,
    total_travel_minutes            INTEGER        NOT NULL,
    total_visit_minutes             INTEGER        NOT NULL,
    total_waiting_minutes           INTEGER        NOT NULL,
    remaining_minutes               INTEGER        NOT NULL,

    candidate_count                 INTEGER        NOT NULL,
    scheduled_count                 INTEGER        NOT NULL,

    algorithm_version               VARCHAR(40)    NOT NULL,
    average_speed_kmh               NUMERIC(6, 2)  NOT NULL,
    fixed_transfer_minutes          INTEGER        NOT NULL,

    generated_at                    TIMESTAMPTZ    NOT NULL,

    CONSTRAINT pk_itineraries
        PRIMARY KEY (id),

    CONSTRAINT uq_itineraries_public_id
        UNIQUE (public_id),

    CONSTRAINT fk_itineraries_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_itineraries_trip
        FOREIGN KEY (trip_id)
            REFERENCES trips (id)
            ON DELETE RESTRICT,

    CONSTRAINT chk_itineraries_window
        CHECK (window_start < window_end),

    CONSTRAINT chk_itineraries_origin_latitude
        CHECK (
            origin_latitude >= -90.0000000
                AND origin_latitude <= 90.0000000
            ),

    CONSTRAINT chk_itineraries_origin_longitude
        CHECK (
            origin_longitude >= -180.0000000
                AND origin_longitude <= 180.0000000
            ),

    CONSTRAINT chk_itineraries_travel_pace
        CHECK (
            travel_pace IN (
                            'RELAXED',
                            'BALANCED',
                            'FAST'
                )
            ),

    CONSTRAINT chk_itineraries_environment_preference
        CHECK (
            environment_preference IN (
                                       'INDOOR',
                                       'OUTDOOR',
                                       'MIXED'
                )
            ),

    CONSTRAINT chk_itineraries_budget
        CHECK (
            initial_budget >= 0.00
                AND total_estimated_cost >= 0.00
                AND total_estimated_cost <= initial_budget
                AND remaining_budget >= 0.00
                AND remaining_budget
                = initial_budget - total_estimated_cost
            ),

    CONSTRAINT chk_itineraries_distance
        CHECK (total_distance_km >= 0.000),

    CONSTRAINT chk_itineraries_minutes
        CHECK (
            total_travel_minutes >= 0
                AND total_visit_minutes >= 0
                AND total_waiting_minutes >= 0
                AND remaining_minutes >= 0
                AND fixed_transfer_minutes >= 0
            ),

    CONSTRAINT chk_itineraries_counts
        CHECK (
            candidate_count >= 0
                AND scheduled_count > 0
                AND scheduled_count <= candidate_count
            ),

    CONSTRAINT chk_itineraries_algorithm_version
        CHECK (algorithm_version = 'GREEDY_V1'),

    CONSTRAINT chk_itineraries_average_speed
        CHECK (average_speed_kmh > 0.00)
);


CREATE INDEX idx_itineraries_user_public_id
    ON itineraries (user_id, public_id);


CREATE INDEX idx_itineraries_trip_id
    ON itineraries (trip_id);


CREATE TABLE itinerary_preferred_categories
(
    itinerary_id    BIGINT NOT NULL,
    category_id     BIGINT NOT NULL,

    CONSTRAINT pk_itinerary_preferred_categories
        PRIMARY KEY (itinerary_id, category_id),

    CONSTRAINT fk_itinerary_preferred_categories_itinerary
        FOREIGN KEY (itinerary_id)
            REFERENCES itineraries (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_itinerary_preferred_categories_category
        FOREIGN KEY (category_id)
            REFERENCES categories (id)
            ON DELETE RESTRICT
);


CREATE INDEX idx_itinerary_preferred_categories_category_id
    ON itinerary_preferred_categories (category_id);