CREATE TABLE itinerary_items
(
    id                                  BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    itinerary_id                        BIGINT          NOT NULL,
    sequence_no                         INTEGER         NOT NULL,

    place_id                            BIGINT          NOT NULL,
    place_name                          VARCHAR(150)    NOT NULL,
    place_slug                          VARCHAR(180)    NOT NULL,
    place_address                       VARCHAR(255)    NOT NULL,
    place_administrative_unit_name      VARCHAR(150)    NOT NULL,
    place_administrative_unit_type      VARCHAR(30)     NOT NULL,

    latitude                            NUMERIC(10, 7)  NOT NULL,
    longitude                           NUMERIC(10, 7)  NOT NULL,
    indoor                              BOOLEAN         NOT NULL,

    base_visit_minutes                  INTEGER         NOT NULL,

    travel_minutes_from_previous        INTEGER         NOT NULL,
    distance_km_from_previous           NUMERIC(10, 3)  NOT NULL,

    arrival_time                        TIME            NOT NULL,
    waiting_minutes                     INTEGER         NOT NULL,
    visit_start                         TIME            NOT NULL,
    visit_end                           TIME            NOT NULL,
    visit_minutes                       INTEGER         NOT NULL,

    estimated_cost                      NUMERIC(12, 2)  NOT NULL,
    selection_score                     NUMERIC(10, 4)  NOT NULL,

    opening_hours_status                VARCHAR(20)     NOT NULL,
    opening_time                        TIME,
    closing_time                        TIME,

    CONSTRAINT pk_itinerary_items
        PRIMARY KEY (id),

    CONSTRAINT fk_itinerary_items_itinerary
        FOREIGN KEY (itinerary_id)
            REFERENCES itineraries (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_itinerary_items_place
        FOREIGN KEY (place_id)
            REFERENCES places (id)
            ON DELETE RESTRICT,

    CONSTRAINT uq_itinerary_items_sequence
        UNIQUE (itinerary_id, sequence_no),

    CONSTRAINT uq_itinerary_items_place
        UNIQUE (itinerary_id, place_id),

    CONSTRAINT chk_itinerary_items_sequence
        CHECK (sequence_no > 0),

    CONSTRAINT chk_itinerary_items_text_snapshots
        CHECK (
            btrim(place_name) <> ''
                AND btrim(place_slug) <> ''
                AND btrim(place_address) <> ''
                AND btrim(
                            place_administrative_unit_name
                    ) <> ''
            ),

    CONSTRAINT chk_itinerary_items_administrative_unit_type
        CHECK (
            place_administrative_unit_type IN (
                                               'WARD',
                                               'COMMUNE',
                                               'SPECIAL_ZONE'
                )
            ),

    CONSTRAINT chk_itinerary_items_latitude
        CHECK (
            latitude >= -90.0000000
                AND latitude <= 90.0000000
            ),

    CONSTRAINT chk_itinerary_items_longitude
        CHECK (
            longitude >= -180.0000000
                AND longitude <= 180.0000000
            ),

    CONSTRAINT chk_itinerary_items_durations
        CHECK (
            base_visit_minutes > 0
                AND travel_minutes_from_previous >= 0
                AND waiting_minutes >= 0
                AND visit_minutes > 0
            ),

    CONSTRAINT chk_itinerary_items_distance
        CHECK (
            distance_km_from_previous >= 0.000
            ),

    CONSTRAINT chk_itinerary_items_cost
        CHECK (
            estimated_cost >= 0.00
            ),

    CONSTRAINT chk_itinerary_items_selection_score
        CHECK (
            selection_score >= 0.0000
                AND selection_score <= 100.0000
            ),

    CONSTRAINT chk_itinerary_items_timeline
        CHECK (
            arrival_time <= visit_start
                AND visit_start < visit_end
            ),

    CONSTRAINT chk_itinerary_items_opening_hours
        CHECK (
            (
                opening_hours_status = 'KNOWN_OPEN'
                    AND opening_time IS NOT NULL
                    AND closing_time IS NOT NULL
                    AND opening_time < closing_time
                    AND visit_start >= opening_time
                    AND visit_end <= closing_time
                )
                OR
            (
                opening_hours_status = 'UNKNOWN'
                    AND opening_time IS NULL
                    AND closing_time IS NULL
                )
            )
);


CREATE INDEX idx_itinerary_items_place_id
    ON itinerary_items (place_id);


CREATE TABLE itinerary_warnings
(
    id                  BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    itinerary_id        BIGINT          NOT NULL,
    item_sequence       INTEGER,
    code                VARCHAR(60)     NOT NULL,
    message             VARCHAR(500)    NOT NULL,
    sort_order          INTEGER         NOT NULL,

    CONSTRAINT pk_itinerary_warnings
        PRIMARY KEY (id),

    CONSTRAINT fk_itinerary_warnings_itinerary
        FOREIGN KEY (itinerary_id)
            REFERENCES itineraries (id)
            ON DELETE CASCADE,

    CONSTRAINT uq_itinerary_warnings_sort_order
        UNIQUE (itinerary_id, sort_order),

    CONSTRAINT chk_itinerary_warnings_item_sequence
        CHECK (
            item_sequence IS NULL
                OR item_sequence > 0
            ),

    CONSTRAINT chk_itinerary_warnings_sort_order
        CHECK (sort_order >= 0),

    CONSTRAINT chk_itinerary_warnings_code
        CHECK (
            code IN (
                     'TRAVEL_TIME_ESTIMATED',
                     'COST_USES_MINIMUM_ESTIMATE',
                     'OPENING_HOURS_UNKNOWN',
                     'UNUSED_TIME_REMAINS',
                     'LIMITED_CATEGORY_COVERAGE'
                )
            ),

    CONSTRAINT chk_itinerary_warnings_message
        CHECK (
            btrim(message) <> ''
            ),

    CONSTRAINT chk_itinerary_warnings_scope
        CHECK (
            (
                code = 'OPENING_HOURS_UNKNOWN'
                    AND item_sequence IS NOT NULL
                )
                OR
            (
                code <> 'OPENING_HOURS_UNKNOWN'
                    AND item_sequence IS NULL
                )
            )
);