CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    slug        VARCHAR(120) NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_categories_name
        UNIQUE (name),

    CONSTRAINT uq_categories_slug
        UNIQUE (slug),

    CONSTRAINT ck_categories_name_not_blank
        CHECK (LENGTH(BTRIM(name)) > 0),

    CONSTRAINT ck_categories_slug_format
        CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),

    CONSTRAINT ck_categories_timestamp_order
        CHECK (updated_at >= created_at)
);
