CREATE TABLE opening_hours
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id    BIGINT   NOT NULL,
    day_of_week SMALLINT NOT NULL,
    open_time   TIME,
    close_time  TIME,
    closed      BOOLEAN  NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_opening_hours_place
        FOREIGN KEY (place_id)
            REFERENCES places (id)
            ON DELETE CASCADE,

    CONSTRAINT uq_opening_hours_place_day
        UNIQUE (place_id, day_of_week),

    CONSTRAINT ck_opening_hours_day
        CHECK (day_of_week BETWEEN 1 AND 7),

    CONSTRAINT ck_opening_hours_state
        CHECK (
            (
                closed = TRUE
                AND open_time IS NULL
                AND close_time IS NULL
            )
            OR
            (
                closed = FALSE
                AND open_time IS NOT NULL
                AND close_time IS NOT NULL
                AND open_time < close_time
            )
        )
);
