INSERT INTO places (
    name,
    slug,
    short_description,
    full_description,
    address,
    administrative_unit_name,
    administrative_unit_type,
    latitude,
    longitude,
    estimated_visit_minutes,
    min_cost,
    max_cost,
    indoor,
    active
) VALUES
    (
        'Demo Art Space',
        'demo-art-space',
        'Dữ liệu minh họa, chưa được xác minh',
        'Địa điểm mô phỏng chỉ phục vụ phát triển và kiểm thử.',
        'Địa chỉ demo 1',
        NULL,
        NULL,
        10.7750000,
        106.7000000,
        90,
        50000,
        150000,
        TRUE,
        TRUE
    ),
    (
        'Demo City Garden',
        'demo-city-garden',
        'Dữ liệu minh họa, chưa được xác minh',
        'Địa điểm mô phỏng chỉ phục vụ phát triển và kiểm thử.',
        'Địa chỉ demo 2',
        NULL,
        NULL,
        10.7800000,
        106.6900000,
        60,
        0,
        50000,
        FALSE,
        TRUE
    ),
    (
        'Demo History Hall',
        'demo-history-hall',
        NULL,
        'Dữ liệu minh họa, chưa được xác minh; chỉ phục vụ phát triển và kiểm thử.',
        'Địa chỉ demo 3',
        NULL,
        NULL,
        10.7700000,
        106.6950000,
        120,
        30000,
        100000,
        TRUE,
        TRUE
    ),
    (
        'Demo Riverside Walk',
        'demo-riverside-walk',
        'Dữ liệu minh họa, chưa được xác minh',
        'Địa điểm mô phỏng chỉ phục vụ phát triển và kiểm thử.',
        'Địa chỉ demo 4',
        NULL,
        NULL,
        10.7900000,
        106.7100000,
        75,
        0,
        80000,
        FALSE,
        TRUE
    ),
    (
        'Demo Science Center',
        'demo-science-center',
        'Dữ liệu minh họa, chưa được xác minh',
        'Địa điểm mô phỏng chỉ phục vụ phát triển và kiểm thử.',
        'Địa chỉ demo 5',
        NULL,
        NULL,
        10.7550000,
        106.6650000,
        100,
        40000,
        120000,
        TRUE,
        TRUE
    ),
    (
        'Demo Temporarily Hidden Place',
        'demo-temporarily-hidden-place',
        'Dữ liệu minh họa, chưa được xác minh',
        'Địa điểm mô phỏng inactive chỉ phục vụ kiểm thử.',
        'Địa chỉ demo 6',
        NULL,
        NULL,
        10.7700000,
        106.6700000,
        45,
        0,
        30000,
        TRUE,
        FALSE
    );
