-- One Trip owns at most one editable working itinerary.
-- Scheduling/calculation data intentionally does not belong in this foundation table.

CREATE TABLE itineraries
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id  UUID        NOT NULL,
    trip_id    BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_itineraries_public_id
        UNIQUE (public_id),

    CONSTRAINT uq_itineraries_trip_id
        UNIQUE (trip_id),

    CONSTRAINT fk_itineraries_trip
        FOREIGN KEY (trip_id)
            REFERENCES trips (id)
            ON DELETE CASCADE,

    CONSTRAINT ck_itineraries_timestamp_order
        CHECK (updated_at >= created_at)
);
