server:
  port: 8080

spring:
  application:
    name: saigon-plan-travel-backend

  datasource:
    url: ${JDBC_DB_URL}
    username: ${JDBC_DB_USERNAME}
    password: ${JDBC_DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always
