name: e2e-tests.yml
on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main
jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: e2e-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
          cache-dependency-path: e2e-tests/pom.xml

      - name: Compile tests
        run: mvn clean test-compile
